### ISSUE TITLE
Adding custom error message if assertion fails

### ISSUE THREAD

**Issue by ctapobep** [hadley/assertthat#15]
Example:

```
assert_that('Dates substraction did not convert into respective units',
  d2 - d1 == 365,
  are_equal(as.integer(difftime(d2, d1, units = 'weeks')), 51),
  are_equal(as.integer(difftime(d2, d1, units = 'days')), 365),
  are_equal(as.integer(difftime(d2, d1, units = 'days')), 365))
```

Expected Result:

> Error: Dates substraction did not convert into respective units. Details:
>   as.integer(difftime(d2, d1, units = "weeks")) not equal to 51

**Comment by jameslamb** [comment]
@hadley we can close this issue. Was addressed by @krlmlr with the addition of `msg` in v0.2.0 (#6 )
