### ISSUE TITLE
"argument is of length zero" case uninformative

### ISSUE THREAD

**Issue by archenemies** [hadley/assertthat#32]
Hello! I just installed your package. I noticed it does better than 'stopifnot' when comparing to a NULL:

    > stopifnot(1==NULL) # No error
    > assert_that(1==NULL)
    Error in if (!res) { : argument is of length zero

This means that I can use it to check that e.g. `nrow(X)==N`, which is great! However, it gives even prettier errors when the argument is FALSE:

    > assert_that(1==2)
    Error: 1 not equal to 2

Are there any plans to, for example, have pretty errors when the argument is of length zero? For example:

    > assert_that(1==NULL)
    Error in "1==NULL" : argument is of length zero

This would make it a bit easier to track down the location of the error, although I guess there's always `traceback()`...

**Comment by hadley** [comment]
You should be using `is.null()` - `==` is for vectorised comparisons.

**Comment by archenemies** [comment]
Which one is best for asserting that an object has 2 rows?

Because nrow(x) could be 2, or 1, or 3, or NULL...

Or maybe instead of `assert_that(nrow(x)==2)`, you want me to write `assert_that(!is.null(nrow(x)) && nrow(x)==2)`?

Anyway, I guess what you are saying is that you have no plans to make the error message "Error in if (!res) { : argument is of length zero" more informative. Thanks for the reply...

**Comment by hadley** [comment]
In that case maybe you want `NROW()`?

**Comment by archenemies** [comment]
Thank you for the tip.

**Comment by archenemies** [comment]
I just wanted to add that, although grateful for the tip, it still seems a bit odd to me to close a feature request on a bug detecting library, on the grounds that "user's code is buggy"...
