### ISSUE TITLE
assert_that with on_failure could be even more user friendly

### ISSUE THREAD

**Issue by kendonB** [hadley/assertthat#38]
I imagined `on_failure` would be allowed to be an argument to `assert_that`.

Something like:

`assert_that(x %% 2 == 1, on_failure = "x is even")`

Hope this helps

**Comment by fsavje** [comment]
This functionality already exists in the form of the `msg` argument to `assert_that`:

```R
assert_that(10 %% 2 == 1, msg = "x is even")
# Error: x is even
```
