### ISSUE TITLE
is.count(Inf) throws an error

### ISSUE THREAD

**Issue by hughjonesd** [hadley/assertthat#42]
```
is.count(Inf)
Error in if (!is.integerish(x)) return(FALSE) : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In is.integerish(x) : NAs introduced by coercion to integer range
```

Using 0.2.0 on R 3.4.1.

**Comment by hughjonesd** [comment]
A possible one liner fix is in `is.integerish`:
`is.integer(x) || (! any(is.infinite(x)) && is.numeric(x) && all(x == as.integer(x)))`

That assumes you think Inf is not an integer.

**Comment by jameslamb** [comment]
@hughjonesd I just added #47 to hopefully address this! Took a slightly different route than the one you suggested, since this problem extends beyond infinite values to just "super big values"

**Comment by hughjonesd** [comment]
Great.

**Comment by jameslamb** [comment]
@hadley we can close this now that #47 was merged. New behavior:

<img width="211" alt="image" src="https://user-images.githubusercontent.com/7608904/41918215-84cd8936-7921-11e8-9fc7-15c25e5e2395.png">
