### ISSUE TITLE
assertthat release?

### ISSUE THREAD

**Issue by jameslamb** [hadley/assertthat#57]
@hadley good morning! Could you do an `assertthat` release to CRAN? I've been running into a few bugs that have been fixed by PRs accepted since 0.2.0 was pushed to CRAN in 2017.

**Comment by hadley** [comment]
There only appears to be one change? https://github.com/hadley/assertthat/blob/master/NEWS.md

**Comment by jameslamb** [comment]
I specifically was running into the things fixed by #55 

I think maybe the author of that PR put his news item in the wrong place (under 0.2.0 release)

**Comment by hadley** [comment]
Do you want to do a PR to fix it? Then I can probably do a release next week.

**Comment by jameslamb** [comment]
Yep! Thank you, sir

**Comment by hadley** [comment]
See #59
