### ISSUE TITLE
Release assertthat 0.2.1

### ISSUE THREAD

**Issue by hadley** [hadley/assertthat#59]
Prepare for release: 
 
* [x] `devtools::check()` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [x] `revdepcheck::revdep_check(num_workers = 4)` 
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release) 
* [x] Handle `has_name()` failures
 
Submit to CRAN: 
 
* [x] `usethis::use_version()` 
* [x] Update `cran-comments.md` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()`

**Comment by hadley** [comment]
@jameslamb the stricter checks in `has_name()` cause dynutils, ExpDE, MOEADr, and prioritizr to fail. Do you want to relax this check, or do you want to inform the maintainers about the problem?

**Comment by jameslamb** [comment]
@hadley thanks for running that, I'll inform the maintainers by email

**Comment by jameslamb** [comment]
@hadley actually wait, I have a (possibly better) idea. I looked at the source code of those four packages, and all of them are doing this:

```
all(assertthat::has_name(x, vector_of_names))
```

If we changed `has_name()` to do that internally, it would still fulfill the goal of #46 (make all assertions return a single TRUE/FALSE) while not breaking _any_ existing code on CRAN. Would you be open to a PR that does that?

So, concretely:

```
x <- list(a = TRUE, b = "hello")

has_name(x, "a")
[1] TRUE

has_name(x, c("a", "b"))
[1] TRUE

has_name(x, c("a", "d"))
[1] FALSE
```

**Comment by hadley** [comment]
Yeah, that'd be great

**Comment by jameslamb** [comment]
created #60

**Comment by hadley** [comment]
@jameslamb CRAN checks picked up a new problem that I missed:

```
    > library(testthat) 
    > library(codyn)
    > test_check("codyn")
    ── 1. Failure: community_stability loads and returns correct result (@test_commu
    `stability_onerep(dat2agg, "subplot")` threw an error with unexpected message.
    Expected match: "df does not have name subplot"
    Actual message: "df does not have all of these name(s): 'subplot'"
```

Would you mind doing a PR to them to fix the problem?

**Comment by jameslamb** [comment]
yep no problem. Will link here when I make it

**Comment by jameslamb** [comment]
Created NCEAS/codyn#111. I was able to do it in a way that makes their tests work with both `assertthat 0.2.0` and 0.2.1, so should be minimally disruptive for them.

**Comment by hadley** [comment]
Perfect, thanks!

**Comment by jameslamb** [comment]
I see this made it to CRAN. @hadley thanks for doing a release!
