### ISSUE TITLE
has_name will return a vector if nm is a vector

### ISSUE THREAD

**Issue by drewhendrickson** [hadley/assertthat#9]
example:

```
t = data.frame("a"=1, "b"=2)
has_name(t, c("a", "b"))
```

returns a vector with two true values. 

This seems to violate the idea that all assertions will return either True or False (from the comments in assert_that.R). I'd suggest either checking the type or length of nm in has_name.

**Comment by jameslamb** [comment]
Can confirm that this inconsistency exists and will break your stuff.

```
assert_that(has_name(t, c("a", "b")))
 Show Traceback
 
 Rerun with Debug
 Error: assert_that: length of assertion is not 1 
```

Other assertion functions in the package break early on bad inputs (without waiting until `assert_that`). For example:

![image](https://user-images.githubusercontent.com/7608904/41811131-4441f98c-76cf-11e8-88fb-013bcc3218b7.png)

I will submit a PR this morning to address this.

**Comment by jameslamb** [comment]
@hadley we can close this now that #46 has been merged. New behavior:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/7608904/41918412-e4f64a00-7921-11e8-8327-4f6d87795793.png">

**Comment by drewhendrickson** [comment]
Awesome.
